Geolocalizacion/Controllers/UbicacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Geolocalizacion.Models;

namespace Geolocalizacion.Controllers
{
    public class UbicacionController : Controller
    {
        private readonly AppDbContext _context;

        public UbicacionController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Ubicacion
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ubicaciones.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> GetAllJson()
        {
            return Json(await _context.Ubicaciones.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> AddMarker(string nombre, decimal latitud, decimal longitud, int temperatura, int humedad)
        {
            Ubicacion ubicacion = new Ubicacion();

            ubicacion.Nombre = nombre;
            ubicacion.Latitud = latitud;
            ubicacion.Longuitud = longitud;
            ubicacion.Humedad = humedad;
            ubicacion.Estado = true;
            ubicacion.Temperatura = temperatura;
            ubicacion.FechaRegistro = DateTime.Now;

            _context.Add(ubicacion);

            await _context.SaveChangesAsync();

            return Json("Ok");
        }

        [HttpPut]
        public async Task<IActionResult> UpdateRegister(int id, string nombre, decimal latitud, decimal longitud, int temperatura, int humedad, DateTime fechaRegistro)
        {
            Ubicacion ubicacion = new Ubicacion();

            ubicacion.Id = id;
            ubicacion.Nombre = nombre;
            ubicacion.Latitud = latitud;
            ubicacion.Longuitud = longitud;
            ubicacion.Temperatura = temperatura;
            ubicacion.Humedad = humedad;
            ubicacion.FechaRegistro = fechaRegistro;
            ubicacion.FechaActualizacion = DateTime.Now;
            ubicacion.Estado = true;

            _context.Update(ubicacion);
            await _context.SaveChangesAsync();

            return Json("Ok");
        }

        [HttpPut]
        public async Task<IActionResult> DisableRegister(int id, string nombre, decimal latitud, decimal longitud, int temperatura, int humedad, DateTime fechaRegistro)
        {
            Ubicacion ubicacion = new Ubicacion();

            ubicacion.Id = id;
            ubicacion.Nombre = nombre;
            ubicacion.Latitud = latitud;
            ubicacion.Longuitud = longitud;
            ubicacion.Temperatura = temperatura;
            ubicacion.Humedad = humedad;
            ubicacion.FechaRegistro = fechaRegistro;
            ubicacion.FechaActualizacion = DateTime.Now;
            ubicacion.Estado = false;

            _context.Update(ubicacion);
            await _context.SaveChangesAsync();

            return Json("Ok");
        }

        // GET: Ubicacion/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicaciones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ubicacion == null)
            {
                return NotFound();
            }

            return View(ubicacion);
        }

        // GET: Ubicacion/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ubicacion/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Latitud,Longuitud,Temperatura,Humedad")] Ubicacion ubicacion)
        {
            if (ModelState.IsValid)
            {
                ubicacion.Estado = true;
                ubicacion.FechaRegistro = DateTime.Now;
                _context.Add(ubicacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            return View(ubicacion);
        }

        //[HttpPost]
        //public int AddMarker()
        //{

        //}

        // GET: Ubicacion/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicaciones.FindAsync(id);
            if (ubicacion == null)
            {
                return NotFound();
            }
            return View(ubicacion);
        }

        // POST: Ubicacion/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Latitud,Longuitud,Temperatura,Humedad")] Ubicacion ubicacion)
        {
            if (id != ubicacion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ubicacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UbicacionExists(ubicacion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ubicacion);
        }

        // GET: Ubicacion/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicaciones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ubicacion == null)
            {
                return NotFound();
            }

            return View(ubicacion);
        }

        // POST: Ubicacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ubicacion = await _context.Ubicaciones.FindAsync(id);
            _context.Ubicaciones.Remove(ubicacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UbicacionExists(int id)
        {
            return _context.Ubicaciones.Any(e => e.Id == id);
        }
    }
}

Geolocalizacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Geolocalizacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link href="~/css/leaflet.contextmenu.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Geolocalizacion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ubicacion" asp-action="Index">Ubicacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Geolocalizacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="~/js/leaflet.contextmenu.min.js"></script>
    <script src="https://kit.fontawesome.com/f92c38b31b.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/js/Mapa.js" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>